### ISSUE TITLE
Weekly Reset

### ISSUE THREAD

**Issue by crusha015** [DennisRas/WeeklyKnowledge#30]
Is it possible to force dump completed weekly tasks for all characters upon logging in any character after weekly reset? It seems right now that the previous week results are not cleared per character until I log into that character, so it would be possible to mistakenly think I had a character completed if I never logged into is this week, and it was still last weeks' quests showing up.

**Comment by DennisRas** [comment]
Hi @crusha015 
Thanks for the feedback.
It's actually supposed to reset upon reset. It's a bug if it didn't.
Are you playing in the US and got into a new week?

**Comment by crusha015** [comment]
Yep, I am on US. I haven't logged into warrior, DK or priest yet today after the reset:
![image](https://github.com/user-attachments/assets/d6bc2c7f-a263-4f30-9acd-181695644c9b)

**Comment by DennisRas** [comment]
Omg I just checked the current live version and the code is indeed there to reset the data, but it's never triggered.
I forgot to trigger the function 😫😞

**Comment by crusha015** [comment]
sounds good. Thanks for the quick response!

**Comment by DennisRas** [comment]
> sounds good. Thanks for the quick response!

I could put up a quick hotfix, so it works, however it would reset for everyone the next time they log in.
That could annoy some people that already logged most of their many characters.

**Comment by DennisRas** [comment]
@crusha015 Quick question: Can you do the Darkmoon Faire quests again or are they completed after reset? (make sure to be logged into a character that did Darkmoon quests if you did any)

**Comment by crusha015** [comment]
I'm good either way. I will be logging into all of my alts soon and it will be all fixed back up anyways. I just wanted to report it because a few weeks from now I'll likely be logging in to some alts less, and was more concerned about it then.

DMF does not reset with the weekly reset. So my druid who I did DMF quests on before reset still has them completed today.

**Comment by DennisRas** [comment]
Thank you. I appreciate it :-)
Someone asked if they were weekly while the event were up, and I had the column description set to Monthly so I was worried it was wrong. You rock.

I'm probably gonna hotfix the weekly reset. An entire region hasn't reset yet.
I may even be able to reset just the characters you haven't logged into since reset and keep the others intact.

**Comment by crusha015** [comment]
Happy to help. Great addon! and I think that's fine idea. Worst case some NA folks will need to log back in to a few characters to re check quests

**Comment by DennisRas** [comment]
I agree with you.
Thank you for taking the time.

**Comment by darthInvad0r** [comment]
The logic isn’t quite correct in the reset function as it nukes darkmoon when that isn’t a weekly. 

I forced it run for myself last night by setting the weekly reset time to 0 if it wasn’t already set, and adding the method to run on startup. 

Anyway, instead of just wiping the complete table, it should probably wipe the weeklys, and darkmoon only if it’s no longer active.

**Comment by DennisRas** [comment]
> The logic isn’t quite correct in the reset function as it nukes darkmoon when that isn’t a weekly. 
> 
> I forced it run for myself last night by setting the weekly reset time to 0 if it wasn’t already set, and adding the method to run on startup. 
> 
> Anyway, instead of just wiping the complete table, it should probably wipe the weeklys, and darkmoon only if it’s no longer active. 

You are correct. I have a local fix for that but haven't pushed it to the repo.

It got a bit late and I'm trying to figure out a way to reset for everyone except for the people/characters that have already logged in since reset (looking for US/EU reset timestamps)

**Comment by darthInvad0r** [comment]
> It got a bit late and I'm trying to figure out a way to reset for everyone except for the people/characters that have already logged in since reset (looking for US/EU reset timestamps)

I don't think you can since it doesn't look like it persists last login times for each user.  Personally i'd rather the data just get nuked with an update.  Better to think you have stuff to do, than to think you've already done it.

**Comment by DennisRas** [comment]
> > It got a bit late and I'm trying to figure out a way to reset for everyone except for the people/characters that have already logged in since reset (looking for US/EU reset timestamps)
> 
> I don't think you can since it doesn't look like it persists last login times for each user.  Personally i'd rather the data just get nuked with an update.  Better to think you have stuff to do, than to think you've already done it.

Each character has a lastUpdate timestamp, which is currently used for sorting until I add table sorting again. Luckily that data has been stored since day 1.

**Comment by darthInvad0r** [comment]
> Each character has a lastUpdate timestamp, which is currently used for sorting until I add table sorting again. Luckily that data has been stored since day 1.

Foresight saves the day.  I was glancing through while at work and missed it :)

**Comment by DennisRas** [comment]
> > Each character has a lastUpdate timestamp, which is currently used for sorting until I add table sorting again. Luckily that data has been stored since day 1.
> 
> Foresight saves the day.  I was glancing through while at work and missed it :)

I really do appreciate you for engaging and taking your time with this. It's some good observations.

Now... Do I just get the seconds to the next reset and subtract a week's worth of seconds to estimate the last reset? 😂 A bit of a gamble otherwise because of timezones and server times.

It's a quick hotfix anyway for the next small version and some few instaloggers once servers were back online may have some of their characters reset, but that's better than everyone waiting another week or manually updating meanwhile.

**Comment by darthInvad0r** [comment]
Yeah subtracting a week from the next reset sounds like enough due diligence to me

**Comment by DennisRas** [comment]
Thank you everyone ❤️ 

![image](https://github.com/user-attachments/assets/064bb658-7211-4b2b-9e17-bf227925c67a)
