### ISSUE TITLE
Micro stuttering

### ISSUE THREAD

**Issue by DennisRas** [DennisRas/WeeklyKnowledge#57]
From CurseForge:

> Since the last update I have some serious microstuttering in the game. It's disabling the addon and going smooth as butter. Does it happen to anyone else?

**Comment by emptyrivers** [comment]
Hey there. In my unending quest to be able to play this game without performance problems, I did identify the source of this micro-stutter. Specifically,`WeeklyKnowledge.Core:Render()` takes about 50,000 microseconds to execute:
![Core:Render() cpu](https://github.com/user-attachments/assets/8dcc7ed8-7ac0-4750-b2fe-6444ca52c97d)
That's more than long enough to notice, and it happens fairly frequently - pretty much anytime you loot anything, there's a noticeable hitch due to WeeklyKnowledge re-rendering its displays, even if they're not currently visible. Monkeypatching the addon such that `WeeklyKnowledge.Main:Render()` and `WeeklyKnowledge.Checklist:Render()` return ASAP if their respective frames are not visible subjectively eliminated the stutters (while the windows aren't visible, of course).

In particular, the main window seems to be the biggest hog, so if you're looking for a good target for optimization, I think you would do well to start with that.

**Comment by emptyrivers** [comment]
Oh, I should clarify - that's 50,000 microseconds to render, when there are 13 characters recorded in the SavedVariables, 9 of which have 2 professions each for a total of 18 rows in the Main window display.

**Comment by DennisRas** [comment]
Thanks for the feedback @emptyrivers 
We already talked on Discord earlier, but wanted to report here that I'm looking into the issue asap.
